# Generated by Django 5.0.1 on 2024-02-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customarticles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста'),
        ),
        migrations.AddField(
            model_name='customarticles',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Forum.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='customarticles',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Forum.tagpost', verbose_name='Тэги'),
        ),
    ]
