# Generated by Django 5.0.1 on 2024-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_tagpost_customarticles_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customarticles',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
