# Generated by Django 5.0.1 on 2024-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_alter_customarticles_slug_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customarticles',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Нет'), (1, 'Да')], default=1, verbose_name='Опубликованно'),
        ),
    ]
