# Generated by Django 5.0.1 on 2024-01-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0006_alter_customarticles_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customarticles',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Forum.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='customarticles',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
