# Generated by Django 5.0.1 on 2024-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_alter_customarticles_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
