# Generated by Django 5.0.1 on 2024-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_rename_genre_id_customarticles_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тэги', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(max_length=128, verbose_name='Тэг'),
        ),
    ]
