# Generated by Django 5.0.1 on 2024-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0010_alter_tagpost_options_alter_tagpost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customarticles',
            name='created_by',
            field=models.CharField(default='admin', max_length=255, verbose_name='Автор поста'),
        ),
        migrations.AlterField(
            model_name='customarticles',
            name='img_src',
            field=models.TextField(blank=True, null=True, verbose_name='Путь до изображения'),
        ),
        migrations.AlterField(
            model_name='customarticles',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Нет'), (True, 'Да')], default=1, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='customarticles',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='customarticles',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Forum.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='customarticles',
            name='text',
            field=models.TextField(default='Эта статья была опубликована без текста', verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='customarticles',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Посещения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_src',
            field=models.TextField(verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='ref',
            field=models.TextField(verbose_name='Ссылка на оригинал'),
        ),
    ]
