# Generated by Django 5.0.1 on 2024-02-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0011_alter_customarticles_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customarticles',
            name='text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
    ]
