# Generated by Django 5.0.1 on 2024-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0012_alter_customarticles_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customarticles',
            name='img_src',
        ),
        migrations.AddField(
            model_name='customarticles',
            name='img',
            field=models.ImageField(blank=True, upload_to='custom_photos/%Y/%m', verbose_name='фото'),
        ),
    ]
